### ISSUE TITLE
Suggestion from Taylor R Campbell - Don't use Z twice

### ISSUE THREAD

**Issue by emanjon** [cfrg/draft-irtf-cfrg-det-sigs-with-noise#5]
>    *  Added note that Z in step f is not reused from step d.

May I suggest using different letters for this, or numbered instances
like Z0 and Z1?  It's confusing to define a function F(m, Z, Z) as
you're doing here where the two Z's are actually different parameters.

https://mailarchive.ietf.org/arch/msg/cfrg/jmfn1b880x7-7gZKb7_uwLvE3oU/

**Comment by emanjon** [comment]
Fixed in main

**Comment by dannyniu** [comment]
Using different `Z` for steps d and f breaks PRNG boundary - RFC-6979 is essentially ECDSA plus a user-seeded HMAC-DRBG, using different `Z`s changes **and breaks** the PRNG algorithm.
