### ISSUE TITLE
Algorithm naming - Comment by Simon Josefsson

### ISSUE THREAD

**Issue by emanjon** [cfrg/draft-irtf-cfrg-det-sigs-with-noise#7]
https://mailarchive.ietf.org/arch/msg/cfrg/EuHdNSQf_bsMWemjvbec-hTbWkw/

I believe this document should not update/modify the core EdDSA/ECDSA
algorithms but instead it should specify new names for the alternative
EdDSA/ECDSA variant it is attempting to introduce.

It would cause confusion to modify a tiny but security-critical piece of
a crypto algorithm, that is only applicable to certain environments, and
continue to use the same name for the new algorithm that has different
security properties.

I suggest using the name 'R* for the variants, e.g., 'REd25519ph',
'REd25519ctx', 'REd25519 etc.

Then any IoT specification that wants to use the REd25519 variant can do
so clearly, and those specifications/implementations that do not want to
use it is not put at risk by using a library that implements 'Ed25519'
that happened to have adopted this modification.

**Comment by cjpatton** [comment]
I think coming up with new names is likely to cause confusion. As an implementer, I would expect two algorithms with different names to be wire incompatible with one another. To the contrary, it sounds like the intent is to keep wire compatibility and just harden nonce generation. (A good goal, I think.)

I think the ideal outcome for this draft would be adoption of the recommendation in cryptographic libraries without users of those libraries having to worry about API-breaking changes. If we do this right, then addressing the threat model is simply a matter of upgrading to the next minor version of the library :)

**Comment by emanjon** [comment]
@cjpatton I agree. Currently we have Randomized ECDSA and Deterministic ECDSA. The document definines Hedged ECDSA. The plan is to call it Hedged EdDSA. More specific names would be Hedged Ed25519ph, Hedged Ed25519ctx, and hedged Ed25519.

**Comment by emanjon** [comment]
Seems to be agreement in the CFRG session at IETF 119 to go with "Hedged EdDSA" or "Hedged Ed25519ph", "Hedged Ed25519ctx", and "Hedged Ed25519" if more specification is needed
